let item = [
    {id:"001",
  itemImage: "img/1.jpg",
  rating: {
    stars: 5.5,
    starIcon: "fa-solid fa-star",
    noOfReviews: 2000,
  },
  companyName: "Company Name 1",
  itemName: "Item Name 1",
  pricing: {
    currenPrice: 606,
    orignalPrice: 1045,
    discountPercentage: 30,
  },
},
{id:"002",
    itemImage: "img/2.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 2" ,
    itemName: "Item Name 2",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
  {id:"003",
    itemImage: "img/3.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 3",
    itemName: "Item Name 3",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
  {id:"004",
    itemImage: "img/4.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 4",
    itemName: "Item Name 4",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
  {id:"005",
    itemImage: "img/5.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 5",
    itemName: "Item Name 5",
    pricing: {
      currenPrice: 606,
      orignalPrice:1045,
      discountPercentage: 42,
    },
  },
  {id:"006",
    itemImage: "img/6.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 6",
    itemName: "Item Name 6",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
  {id:"007",
    itemImage: "img/7.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 7",
    itemName: "Item Name 7",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
  {id:"008",
    itemImage: "img/8.jpg",
    rating: {
      stars: 4.5,
      starIcon: "fa-solid fa-star",
      noOfReviews: 1400,
    },
    companyName: "Company Name 8",
    itemName: "Item Name 8",
    pricing: {
      currenPrice: 606,
      orignalPrice: 1045,
      discountPercentage: 42,
    },
  },
];